Support tuples as result type
tarantool/crud pull request #10
Opened 2020-09-23 14:08 UTC by savolgin

Added support for operations results as tuples. Issue #6

2020-09-24 06:18 UTC, olegrok reviewed
Thanks for your patch!

Do you understand that `crud.init` is executed on _storage_ but all flattening/unflattening takes place on the router?

It makes you approach a bit wrong. Also I don't like "tuples_as_map" name. IMO it should be something like "use_tomap=true/false" (maybe @dokshina will purpose a better name for it).

Next, seems the correct way to solve your task - it save "call" result to "buffer" and then convert to formatted tuple (since 2.2 format is stored in conn.space.<space_name>._cdata_format variable). I'm not sure it's easy to implement (https://github.com/tarantool/tarantool/blob/0018398db632b3d0131ca8dcc1f65315039bbf98/src/box/lua/net_box.lua#L73) and some internal magic is required. But after that user will get formatted tuples that will look like simple tuples from spaces.

2020-09-24 08:16 UTC, dokshina commented
I agree with @olegrok.

Since your changes affects current API, I would like you to add RFC to the issue and describe new flags and configuring router. We need to discuss this changes. I sure that it's the right way to make `CRUD` pretty and useful.

1. About the new flag name, I suggest `tomap` or `use_tomap`, or maybe `tuples_tomap`. I will cal it `tomap` in this comment.

2. Yes, `crud.init` is called on storage which operates with tuples and know nothing about router's staff such as current select state or tuples flattening/unflattenning. There is no reason to pass  `tomap` parameter to `crud.init`. I like adding a new flag to each call, and I agree that it will be useful to set it once. Maybe we need something like `crud.cfg` or `crud.router.cfg` to specify such "global" options on router side.

3. I would be great to return formatted tuples, but it can be implemented later in a separated patch.

2020-09-24 08:59 UTC, knazarov commented
I'd argue that the key problem here is with the connectors. When you use connectors to access regular non-sharded Tarantool, you get tuples that have "format", because the server provides you with it.
If the router doesn't have the format for those tuples, it will strip the format, and you'd receive tuples on the connector side that don't have information about field names. 

This is a major usability problem and (i suppose) the reason why current implementation uses maps. 

I understand that maps perform worse than tuples, and I agree that we should support tuples as well (maybe even by default), but we should somehow solve the problem with the format. Which brings us to the https://github.com/tarantool/ddl module. I expect that for this to be possible, we need to have the same spaces created on routers.

2020-09-24 09:06 UTC, akudiyar commented
Not all connectors support schema loading, and not all spaces have the schema defined. So working with standard tuples is more basic than working with tuples with fields.

Although, I agree with @knazarov about the lack of schema on routers, and we overcome this by providing recommendations of using DDL module for retrieving schemas or writing custom API functions when using the new Java connector. The "tomap" conversion is therefore performed inside the connector, which allows working seamlessly with any setup.

2020-09-24 09:51 UTC, akudiyar commented
@dokshina The short proposal is described in #6 . I suggest renaming the option and so not set any options in init -- let it always be an explicit option for each request.

Is this enough?

2020-09-24 15:58 UTC, akudiyar requested changes

2020-09-25 11:37 UTC, savolgin commented on README.md
> +All storage replica sets should call `crud.init(opts)`
Global opts removed

2020-09-25 11:38 UTC, savolgin commented on crud/common/utils.lua
> +    local result_as_map = as_map
Parameter removed

2020-09-25 11:39 UTC, savolgin commented on crud/common/utils.lua
> +    if result_as_map then
fixed: unflatten not calling for if tuples_tomap == false

2020-09-25 11:40 UTC, savolgin commented on crud/delete.lua
> +local format_tuples_as_map = true
removed

2020-09-25 12:28 UTC, akudiyar approved these changes

2020-10-06 12:38 UTC, dokshina commented
I think, we can close this PR.

It was implemented in #39 (merged) and #40, #42, #43 PRs that will be merged soon.

2020-10-06 12:38 UTC, closed without merging