Fix fail of select when there are no indexes in space
tarantool/crud pull request #258
Opened 2022-02-09 08:41 UTC by AnaNek

This fix checks if space contains indexes and if there are
no indexes in space `select` returns error
`Space has no indexes,space should have primary and bucket_id indexes`.

Closes #257

2022-02-09 09:00 UTC, Totktonada commented on crud/select/plan.lua
> +    end
AFAIU, we're not interested in bucket_id *index* in crud (it is for vshard rebalancer).

2022-02-14 16:39 UTC, ligurio requested changes

2022-02-15 12:02 UTC, AnaNek commented on crud/select/plan.lua
> +    if space_indexes == nil or not next(space_indexes) then
I need it to check if `space_indexes` is an empty table. If space has no indexes we have empty table `space.index`.

2022-02-15 17:04 UTC, Totktonada commented on crud/select/plan.lua
> +    end
Thanks for the clarification! It looks ok now.

2022-02-15 17:05 UTC, Totktonada commented on crud/select/plan.lua
> +    if space_indexes == nil or not next(space_indexes) then
I don't know a better way to check a table for emptiness.

2022-02-15 17:30 UTC, Totktonada commented
I had a doubt here: if an index will be added later, will we reload the schema to see the index at next request? I see now, that it will work:

https://github.com/tarantool/crud/blob/fb10ea967be3b8e5199e8674e699694af3661c5b/crud/select/compat/select.lua#L59-L69

https://github.com/tarantool/crud/blob/fb10ea967be3b8e5199e8674e699694af3661c5b/crud/select/compat/select_old.lua#L111-L122

(The third return value `true` means 'reload if the schema was updated'.)

2022-02-15 20:24 UTC, Totktonada commented
Forgot to mention: please, update the commit message and the pull request descriptions — they mention the error message from the old version of this patch.

2022-02-16 08:18 UTC, AnaNek commented
> Forgot to mention: please, update the commit message and the pull request descriptions — they mention the error message from the old version of this patch.

Done

2022-02-17 06:11 UTC, ligurio commented on crud/select/plan.lua
> +    if space_indexes == nil or not next(space_indexes) then
`table.getn()`?

2022-02-17 06:11 UTC, ligurio approved these changes

2022-02-17 07:00 UTC, Totktonada commented on crud/select/plan.lua
> +    if space_indexes == nil or not next(space_indexes) then
```lua
tarantool> table.getn({})
---
- 0
...

tarantool> table.getn({foo = 'bar'})
---
- 0
...
```

2022-02-17 07:01 UTC, merged